In [ ]:
import pandas as pd
import numpy as np
from google.colab import files

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
file1 = files.upload()

Saving enhanced_anxiety_dataset.csv to enhanced_anxiety_dataset (2).csv


In [ ]:
data=pd.read_csv("enhanced_anxiety_dataset.csv")
data.head(6)

Age  Gender Occupation  Sleep Hours  Physical Activity (hrs/week)  \
0   29  Female     Artist          6.0                           2.7   
1   46   Other      Nurse          6.2                           5.7   
2   64    Male      Other          5.0                           3.7   
3   20  Female  Scientist          5.8                           2.8   
4   49  Female      Other          8.2                           2.3   
5   53    Male      Other          6.4                           6.5   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week) Smoking  \
0                       181                                 10     Yes   
1                       200                                  8     Yes   
2                       117                                  4      No   
3                       360                                  6     Yes   
4                       247                                  4     Yes   
5                       235                                  2      No   

  Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  \
0                        No                   10               114   
1                       Yes                    1                62   
2                       Yes                    1                91   
3                        No                    4                86   
4                        No                    1                98   
5                        No                    9                84   

   Breathing Rate (breaths/min)  Sweating Level (1-5) Dizziness Medication  \
0                            14                     4        No        Yes   
1                            23                     2       Yes         No   
2                            28                     3        No         No   
3                            17                     3        No         No   
4                            19                     4       Yes        Yes   
5                            14                     3        No        Yes   

   Therapy Sessions (per month) Recent Major Life Event  Diet Quality (1-10)  \
0                             3                     Yes                    7   
1                             2                      No                    8   
2                             1                     Yes                    1   
3                             0                      No                    1   
4                             1                      No                    3   
5                             2                     Yes                    5   

   Anxiety Level (1-10)  
0                   5.0  
1                   3.0  
2                   1.0  
3                   2.0  
4                   1.0  
5                   4.0

In [ ]:
data.isnull().sum()

Age                                  0
Gender                               0
Occupation                           0
Sleep Hours                          0
Physical Activity (hrs/week)         0
Caffeine Intake (mg/day)             0
Alcohol Consumption (drinks/week)    0
Smoking                              0
Family History of Anxiety            0
Stress Level (1-10)                  0
Heart Rate (bpm)                     0
Breathing Rate (breaths/min)         0
Sweating Level (1-5)                 0
Dizziness                            0
Medication                           0
Therapy Sessions (per month)         0
Recent Major Life Event              0
Diet Quality (1-10)                  0
Anxiety Level (1-10)                 0
dtype: int64

In [ ]:
data.shape

(11000, 19)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 19 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Age                                11000 non-null  int64  
 1   Gender                             11000 non-null  object 
 2   Occupation                         11000 non-null  object 
 3   Sleep Hours                        11000 non-null  float64
 4   Physical Activity (hrs/week)       11000 non-null  float64
 5   Caffeine Intake (mg/day)           11000 non-null  int64  
 6   Alcohol Consumption (drinks/week)  11000 non-null  int64  
 7   Smoking                            11000 non-null  object 
 8   Family History of Anxiety          11000 non-null  object 
 9   Stress Level (1-10)                11000 non-null  int64  
 10  Heart Rate (bpm)                   11000 non-null  int64  
 11  Breathing Rate (breaths/min)       11000 non-null  int

In [ ]:
data["Anxiety Level (1-10)"].value_counts()

Anxiety Level (1-10)
4.0     2416
3.0     2407
2.0     1756
5.0     1629
1.0     1039
6.0      616
8.0      363
9.0      329
10.0     322
7.0      123
Name: count, dtype: int64

In [ ]:
print(data.columns.tolist())

['Age', 'Gender', 'Occupation', 'Sleep Hours', 'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)', 'Alcohol Consumption (drinks/week)', 'Smoking', 'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)', 'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness', 'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event', 'Diet Quality (1-10)', 'Anxiety Level (1-10)']


In [ ]:
data["Anxiety"] = data.apply(lambda x: 1 if x['Anxiety Level (1-10)'] >=5 else 0, axis=1)
data.head(5)

Age  Gender Occupation  Sleep Hours  Physical Activity (hrs/week)  \
0   29  Female     Artist          6.0                           2.7   
1   46   Other      Nurse          6.2                           5.7   
2   64    Male      Other          5.0                           3.7   
3   20  Female  Scientist          5.8                           2.8   
4   49  Female      Other          8.2                           2.3   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week) Smoking  \
0                       181                                 10     Yes   
1                       200                                  8     Yes   
2                       117                                  4      No   
3                       360                                  6     Yes   
4                       247                                  4     Yes   

  Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  \
0                        No                   10               114   
1                       Yes                    1                62   
2                       Yes                    1                91   
3                        No                    4                86   
4                        No                    1                98   

   Breathing Rate (breaths/min)  Sweating Level (1-5) Dizziness Medication  \
0                            14                     4        No        Yes   
1                            23                     2       Yes         No   
2                            28                     3        No         No   
3                            17                     3        No         No   
4                            19                     4       Yes        Yes   

   Therapy Sessions (per month) Recent Major Life Event  Diet Quality (1-10)  \
0                             3                     Yes                    7   
1                             2                      No                    8   
2                             1                     Yes                    1   
3                             0                      No                    1   
4                             1                      No                    3   

   Anxiety Level (1-10)  Anxiety  
0                   5.0        1  
1                   3.0        0  
2                   1.0        0  
3                   2.0        0  
4                   1.0        0

In [ ]:
data["Anxiety"].value_counts()

Anxiety
0    7618
1    3382
Name: count, dtype: int64

In [ ]:
data.head()

Age  Gender Occupation  Sleep Hours  Physical Activity (hrs/week)  \
0   29  Female     Artist          6.0                           2.7   
1   46   Other      Nurse          6.2                           5.7   
2   64    Male      Other          5.0                           3.7   
3   20  Female  Scientist          5.8                           2.8   
4   49  Female      Other          8.2                           2.3   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week) Smoking  \
0                       181                                 10     Yes   
1                       200                                  8     Yes   
2                       117                                  4      No   
3                       360                                  6     Yes   
4                       247                                  4     Yes   

  Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  \
0                        No                   10               114   
1                       Yes                    1                62   
2                       Yes                    1                91   
3                        No                    4                86   
4                        No                    1                98   

   Breathing Rate (breaths/min)  Sweating Level (1-5) Dizziness Medication  \
0                            14                     4        No        Yes   
1                            23                     2       Yes         No   
2                            28                     3        No         No   
3                            17                     3        No         No   
4                            19                     4       Yes        Yes   

   Therapy Sessions (per month) Recent Major Life Event  Diet Quality (1-10)  \
0                             3                     Yes                    7   
1                             2                      No                    8   
2                             1                     Yes                    1   
3                             0                      No                    1   
4                             1                      No                    3   

   Anxiety Level (1-10)  Anxiety  
0                   5.0        1  
1                   3.0        0  
2                   1.0        0  
3                   2.0        0  
4                   1.0        0

In [ ]:
binary_columns = ['Gender','Smoking', 'Family History of Anxiety', 'Dizziness',
                 'Medication', 'Recent Major Life Event']
le = LabelEncoder()
for col in binary_columns:
  data[col]=le.fit_transform(data[col])
occupation_dummies = pd.get_dummies(data['Occupation'], prefix="Occupation")
data=pd.concat([data, occupation_dummies], axis=1)
data=data.drop("Occupation", axis=1)
print(data.head())
print(data.columns.tolist())

   Age  Gender  Sleep Hours  Physical Activity (hrs/week)  \
0   29       0          6.0                           2.7   
1   46       2          6.2                           5.7   
2   64       1          5.0                           3.7   
3   20       0          5.8                           2.8   
4   49       0          8.2                           2.3   

   Caffeine Intake (mg/day)  Alcohol Consumption (drinks/week)  Smoking  \
0                       181                                 10        1   
1                       200                                  8        1   
2                       117                                  4        0   
3                       360                                  6        1   
4                       247                                  4        1   

   Family History of Anxiety  Stress Level (1-10)  Heart Rate (bpm)  ...  \
0                          0                   10               114  ...   
1                          1  

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11000 entries, 0 to 10999
Data columns (total 32 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Age                                11000 non-null  int64  
 1   Gender                             11000 non-null  int64  
 2   Sleep Hours                        11000 non-null  float64
 3   Physical Activity (hrs/week)       11000 non-null  float64
 4   Caffeine Intake (mg/day)           11000 non-null  int64  
 5   Alcohol Consumption (drinks/week)  11000 non-null  int64  
 6   Smoking                            11000 non-null  int64  
 7   Family History of Anxiety          11000 non-null  int64  
 8   Stress Level (1-10)                11000 non-null  int64  
 9   Heart Rate (bpm)                   11000 non-null  int64  
 10  Breathing Rate (breaths/min)       11000 non-null  int64  
 11  Sweating Level (1-5)               11000 non-null  int

In [ ]:
print(data.corr()['Anxiety'].sort_values(ascending = False))

Anxiety                              1.000000
Anxiety Level (1-10)                 0.788804
Stress Level (1-10)                  0.579902
Therapy Sessions (per month)         0.355498
Caffeine Intake (mg/day)             0.258473
Family History of Anxiety            0.147783
Heart Rate (bpm)                     0.108202
Breathing Rate (breaths/min)         0.100478
Sweating Level (1-5)                 0.095954
Alcohol Consumption (drinks/week)    0.064133
Smoking                              0.057689
Dizziness                            0.052477
Recent Major Life Event              0.048549
Medication                           0.034281
Occupation_Doctor                    0.032696
Occupation_Lawyer                    0.031903
Occupation_Engineer                  0.028216
Occupation_Scientist                 0.023245
Gender                               0.002405
Occupation_Freelancer               -0.000480
Occupation_Student                  -0.001414
Occupation_Nurse                  

In [ ]:
y=data["Anxiety"]
features=data.drop(['Anxiety','Anxiety Level (1-10)'], axis=1)
print("Target shape : ",y.shape)
print("Feature shape : ",features.shape)

Target shape :  (11000,)
Feature shape :  (11000, 30)


In [ ]:
sc = StandardScaler()
x=sc.fit_transform(features)

In [ ]:
x=pd.DataFrame(x, columns=features.columns)
print(x.columns.tolist())

['Age', 'Gender', 'Sleep Hours', 'Physical Activity (hrs/week)', 'Caffeine Intake (mg/day)', 'Alcohol Consumption (drinks/week)', 'Smoking', 'Family History of Anxiety', 'Stress Level (1-10)', 'Heart Rate (bpm)', 'Breathing Rate (breaths/min)', 'Sweating Level (1-5)', 'Dizziness', 'Medication', 'Therapy Sessions (per month)', 'Recent Major Life Event', 'Diet Quality (1-10)', 'Occupation_Artist', 'Occupation_Athlete', 'Occupation_Chef', 'Occupation_Doctor', 'Occupation_Engineer', 'Occupation_Freelancer', 'Occupation_Lawyer', 'Occupation_Musician', 'Occupation_Nurse', 'Occupation_Other', 'Occupation_Scientist', 'Occupation_Student', 'Occupation_Teacher']


In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size= 0.2, stratify=y)
print("training data size : ",xtrain.shape)
print("test data size : ",xtest.shape)

training data size :  (8800, 30)
test data size :  (2200, 30)


In [ ]:
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
ypred=lr.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for Logistic Regression : ",round(accuracy,2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for Logistic Regression :  0.84
Confusion matrix : 
 [[1388  136]
 [ 220  456]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.86      0.91      0.89      1524
           1       0.77      0.67      0.72       676

    accuracy                           0.84      2200
   macro avg       0.82      0.79      0.80      2200
weighted avg       0.83      0.84      0.83      2200



In [ ]:
svc = SVC(kernel='linear')
svc.fit(xtrain,ytrain)
ypred=svc.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for Support Vector Classifier : ",round(accuracy, 2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for Support Vector Classifier :  0.84
Confusion matrix : 
 [[1387  137]
 [ 218  458]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.86      0.91      0.89      1524
           1       0.77      0.68      0.72       676

    accuracy                           0.84      2200
   macro avg       0.82      0.79      0.80      2200
weighted avg       0.84      0.84      0.84      2200



In [ ]:
nb = GaussianNB()
nb.fit(xtrain,ytrain)
ypred=nb.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for Naive byes Classifier : ",round(accuracy, 2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for Naive byes Classifier :  0.81
Confusion matrix : 
 [[1374  150]
 [ 270  406]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.84      0.90      0.87      1524
           1       0.73      0.60      0.66       676

    accuracy                           0.81      2200
   macro avg       0.78      0.75      0.76      2200
weighted avg       0.80      0.81      0.80      2200



In [ ]:
rf = RandomForestClassifier(n_estimators=100,
    max_depth=10,
    random_state=42)
rf.fit(xtrain,ytrain)
ypred=rf.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for Random Forest Classifier : ",round(accuracy, 2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for Random Forest Classifier :  0.83
Confusion matrix : 
 [[1435   89]
 [ 276  400]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.84      0.94      0.89      1524
           1       0.82      0.59      0.69       676

    accuracy                           0.83      2200
   macro avg       0.83      0.77      0.79      2200
weighted avg       0.83      0.83      0.83      2200



In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(xtrain,ytrain)
ypred=knn.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for KNeighbors Classifier : ",round(accuracy, 2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for KNeighbors Classifier :  0.79
Confusion matrix : 
 [[1399  125]
 [ 336  340]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.92      0.86      1524
           1       0.73      0.50      0.60       676

    accuracy                           0.79      2200
   macro avg       0.77      0.71      0.73      2200
weighted avg       0.78      0.79      0.78      2200



To improve the accuracy and model performance of KNeighbors classifier model

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid={
    'n_neighbors': range(3,20),
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}
knngrid = GridSearchCV(estimator=knn, param_grid = param_grid, cv =5, scoring='accuracy', verbose=1)
knngrid.fit(xtrain,ytrain)

Fitting 5 folds for each of 102 candidates, totalling 510 fits


GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': range(3, 20),
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=1)

In [ ]:
ypred = knngrid.predict(xtest)
accuracy=accuracy_score(ytest,ypred)
print("Accuracy score for KNeighbors Classifier : ",round(accuracy, 2))
print("Confusion matrix : \n", confusion_matrix(ytest,ypred))
print("Classification Report : \n", classification_report(ytest,ypred))

Accuracy score for KNeighbors Classifier :  0.8
Confusion matrix : 
 [[1441   83]
 [ 348  328]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.81      0.95      0.87      1524
           1       0.80      0.49      0.60       676

    accuracy                           0.80      2200
   macro avg       0.80      0.72      0.74      2200
weighted avg       0.80      0.80      0.79      2200

